language: node
node_js:
- node
cache:
  yarn: true
  directories:
  - node_modules
script:
- yarn install
- yarn run build
- ls build
deploy:
  provider: s3
  access_key_id: AKIAJLPX77ICVZALUXEA
  secret_access_key:
    secure: iGPF3gILjXRSI7IcP3GmMW7WOgsZsUPimR6vqBAnPvcg4fpiC//HdZ1qWISvZLEMYBxAUxPkZzhJc14SpAHOZg8uBr0i4Q7YXXSn78dYpb5wN8JUzEaRf0FsPPHc6RN42r5kwfZWqdn+CvE6fDfwOYvv+M3TZnvcOeRdNGpUTQMhjVrESO7HFZvevEKvoUi3mTF21srT9K1y+9OkUyDzRPErS7Ig36v0ekVcHQxiKce1tdIJTY9OizWO5PjMYacYILUmb0vJFhC1RsIV6HvtQOKSBZpfaqT/UOEK4oIHe0sKAuuVw3kpDmnTqUQqjafz8FvXyGHqkNOGzYYiDRv/GF3+fgLeH0U1+mTp6hoiCfSLcnNH/VYxVgzSYEHmAMm0YxwRITp7yx+uL95U68/pOdHde+l6iFWJvtqT13r/reuq+wVeOZRy2SDTgfj9HKVHhLU86RLbvzcfXZty20LulYRLg5x4Vy3lngo2qWN01xoBxI1UpfBH0Cl6xbEXkBfWKmUbLVx4R3mwHJV4nOypxUZfkn1dDGfARfuDWln8oee3Bzq/7oJv8ragx0nsiGD3p2iQXLOZXw1UzsL3Y4G1/grYLA7NRvzspxKOxp2Z0LlbTz9QtMcBND2EfQO82zq3uRGLQ5xdehJTB9yWzl/lefgNFt8HeTyFjaXpGh3Tzv4=
  bucket: comicstore
  acl: public_read
  skip_cleanup: true
  local_dir: build
branches:
  only:
  - master
