language: node
node_js:
- node
cache:
  yarn: true
  directories:
  - node_modules
script:
- yarn install
- yarn run build
- ls build
before_deploy:
  - rvm 1.9.3 do gem install aws-sdk -v 2.1.36
deploy:
  provider: s3
  access_key_id: "AKIAJ7W6BGR4M5AEWQIQ"
  secret_access_key:
    secure: "RnWXDB3qn65XPasHZyVi134hzQWncckbqZqI4kphanEMmOGa3tv+AB4b7W83yNUB89RGY5eYri+IKMBLiuAOYwANZQFdbFSd/98CLrqrBR3aS/io0d682ONdZDRP62hQoyF7ZdGSpG8YOBxlukwVK5KFhJk+qPs+TePhyz9fQPdHBJGdIsY4NkQHw4H1dS7ywqEXCB2SnznVWHHgMfKimmOKkM0eE417Es4KPK4IsXEI4916Et7iLHJpMonqOTXmFrAo1C9OAo4gA9Ry1j8xkuWJocBHUzacVPd02C4yEHKYLEVJBx+cmVjXfznQ8jRSEa3R99EOA/aVt1muTJvArnVYKpuhW/QlmaDVj4cWt6WFZgJVqpkRAks6AxtWK3ti8DjI64DlVcP4CJBvrkA0NWf/xl4kXEH642Bxv5miKVQgL16durbDvWZiPJVae/vYM4smwans9ba4iPeaXfaVAVSqtVm0/UlX+/Dkc7OkV+H9TSQ0iScmmjv49Uk78pf4OqENEPZZhlEHq70kl54tMa9Vs1cWb0qai89bD1/lRjybaCCbBadXTDprlRjx3B6VIDDkmhE8UFdtR/tPf7i1Bxoioj+kXFdTc3XyYp3oXZHQ9+ncG7aQ8xWyZzvO6BSKXbTyi2DicPaJvqJyOZwO43Fpa/YsauPc2nrkvPTWKtI="
  region: "eu-west-1"
  bucket: "comicstore"
  skip_cleanup: true
  local_dir: build
branches:
  only:
  - master
