language: node
node_js:
- node
cache:
  yarn: true
  directories:
  - node_modules
script:
- yarn install
- yarn run build
- ls build
deploy:
  provider: s3
  access_key_id: "AKIAJ7W6BGR4M5AEWQIQ"
  secret_access_key:
    secure: "fLg0goyK/4SD5tq8ler81kogBnus/FRkGMhU9jf++1EMa2Iy/3AH4KE9OWvUH9KfmIxWRdq3/l0N+VlrtIqyntKCph+ZPjo0oIpN6uPligWLL5q5NaaEfNQrn59J6Wy/gymgtrLJTbKjSKfYwxxp1RIsW2lBVkrr+aV3gmwsKK0hDWrl7emk52QoXfhl9Y9+3y2ddZKacKP+m1ipMqFisqKMrWlokfFZGDjc2dTuvGtHKVLml3LA1zMGD0gDkBO1+B0oz920d6g9OSnIYn5kE/qVELRqP1bYTcHV+ClGUhGn97M/fXYniCWXrlAELzzaRPkIp2d65QB9LI6MdHhPjPExR1+TiNRPbiabYvOy0PDJBC9rClHfBcQ/v2rnZGrMJIILzL5+fQW3nWA1ITeyfB3ZBy4kz8onLL/lM5YmYK6a9ay6eoeZ5463TrOBczDsPblYQs5F4atlRuGk/o9ILdZnR2lohPp9Lm3W0WUcJF6KeJs6PZ6XrkFSuaLM+5tR9Gge8OYeMABJU+ccL9uud9z20kpatsiP4Wz0OVDw1vcWi43VDLGMEMuj/TtQ6EukgGZ3hu2YktDi0ZPOwz+B2QtQoexAakL+9CZ4+Grq1AVUapDuzaPlaImH3zUlIa1EabKK7YXzfTYDNUBQ59Qp93I6xzDTDyR3SQlOd0q9nbo="  
  bucket: "comicstore"
  acl: public_read
  skip_cleanup: true
  local_dir: build
branches:
  only:
  - master
