language: node_js
node_js:
  - node
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn run build
  - ls build
deploy:
   provider: s3                         
  access_key_id: "AKIAJLPX77ICVZALUXEA"
  secret_access_key:
    secure: xI5TjT4H1oOUSX1O+YbB7xGB60lIGkeyjUKvAMOWCCrKBHy0DpK14tqKDM8q+OFnyc1rewlArT6JLEcmFsjiAHbhERcnWw+hyDD0asKide2mprKQtrb+9EEVJT3t+TjedDSb/wIvAJdXXP5cf57npbplaVp9dagocgtb/TVXwiW+UkLJYLYtIWQGuHUNXrB106dtU/UB1HMOXdV7mbGzWfua+7R8pPCh224X+TNbmxGyJ290Mb/GmH+Z+I3Zku4eyJr+QVR6Sxhg4mPXW5KGGXcHECGY8yckDqPjww7VO+5BVutvQ8G0llkhSUioMTp9FNHS+YFgpPawuXQK5WKSVWMolbfwc2+JoH7UQCf77lf1Ah2MQbFVxC1u6fNVj2tEpmg1LB48dMnDLyjI/2XfPNv9pcfC4+o7f3hlnuombDqI1kkoJGCFsUCHiZE/763i7ZPbKhSajWYs3sS3esFzkf6gj4MwSPblfg0wsQ6N5jgpP3DnPLBiKvAhcTSGf+SPEDXBUDx2Mykx9U7xF1BOs9GhImfLJMrst0g1UADUPe1SH4F2U6oC+1ybW1iSArNyt46RClXoPZN6tO1GYHQF1cGqGiBYCHZ54bxFef5HMdbcS2ufDYp1/FH74/Ur7qqFANswI1bDoI9PZvF4EkXrkARptnWtn9jYizioBjr/5L8=
  bucket: "comicstore"
  acl: public_read
  skip_cleanup: true
  local_dir: build
branches:
  only:
    - master