language: node
node_js:
- node
cache:
  yarn: true
  directories:
  - node_modules
script:
- yarn install
- yarn run build
- ls build
deploy:
  provider: s3
  access_key_id: AKIAJ7W6BGR4M5AEWQIQ
  secret_access_key:
    secure: jrOJ7VypzOKTYcEwk0ccHsFauJFLvmNvl55/TPy8YERUZ+nm++u7nSAsWTMChEeTKh0M/H5eu4dWlasGDwyDE9QuWVCNJ9ockQH1FA/OGGO3p6L1d3ZmjkjjvBdQOmZPVk9cmiiHv293PBYsuQgvOh0edFK2+tLn1bn8ojbU/3tKoprVv2nr/yVxL2YiGTCBBOFVXl2cnnTaZywAsMKwmNZ5RZfJ7S8jZgi9a+HdDU8gE6M/4X8isgteD9g4I2t9nnxErpQAEdQGxm4clKDma30r8gbmHJYUtzI78M1XuUx/EfuF1Y49Jxa9D1W8Gi6gRklZ2C7GhjFQS1/t8ajG3K7kBxYjG9vhDldtwA5geW0RIPXURt4cTdxgPASsgtFYAT/RJKDtORHlBmWHND91Gmqx7XX0QfPzvkRQgzPHzN9xzjhBGIi4h2Vajz+iiJvwbrN23H6tgEO6GV3jbT/3mAXKXzOVP7c4Z3Y5SJjCKRZdads+DZnNAdnH8mYJJn/TTLmyf9++YERRqG85ik/Eb3H8WfPifD5O6hK6xTelUl14UO8wYUarQMUiaVxmCARRHLBn/JSxUXoJx+F8Lc9PC3OqIumHkyj41uitgd0oEx/UUTH8pBFKmAM1EUC7wfEkdf2Kyju5fyQGVMcknzV0vzZWTLwfsT5dNuPtPmGH5qE=
  bucket: comicstore
  acl: public_read
  skip_cleanup: true
  local_dir: build
branches:
  only:
  - master
