language: node
node_js:
- node
cache:
  yarn: true
  directories:
  - node_modules
script:
- yarn install
- yarn run build
- ls build
deploy:
  provider: s3
  access_key_id: "AKIAJ7W6BGR4M5AEWQIQ"
  secret_access_key:
    secure: "S2rjrRVMOumdsm4+UwaYekvTruU243Pw0kvo38Y7jvkrMYOb5VwCJUGgG3fep8J+hUZ10bOH44B6Qp0HTeP75tdZcG4lMq+MJ3cveMcj2g0c1VSVWpivp5sjgtdLXNvUJwlP5Fmu65VUXYzZaDVzog7iUlMgR4kSkcPR6AcEkWa7w/g8HKwkYccSKeywD+yWGcJVSaOk8JNQk4DAE1qnpQ2sPoEBUO+ju95ooZXyJJ8JLwpZfiZsFl5XMGYCkF79mU67kaahcbB075MhsdJsjAnIq9KAnEZd910aPGRXjqdlWuDLJLzuJc4x59eCFqcEwmUILvCSZJ5JnHsrqmlBeYgkObFhhhMK3kR5kABZy+fUQbCoLk9zBx2L4S2BVR0TtFwRmtVRQFl8JWcUP7VFrxoyrAppGtkkuibKu0OGYDudthqKwIHVJdGpTwWO8wE6N1XDj7qfI7MXqSAb+Z5bYj2B6ezmLM+BDvj0l4pOgVwQbNd0Wun0XcUQVHQpA0ADPTyzSFDcfYiBpv2eUqQrvP6JF9xg+/8GGfPhBmyP66lgw1b/rKr9suJua7qOr2u8bfV9y/E4UFXMr0HE1dVYUIzEFsC9JRAh3i3SCnAoyjJYyoslKVaYDGbIO+HMDVGf8zPW4J6ymZtbfAkuSKoSi22IGvBKiSXXAN3PpIgkP/4="  bucket: "comicstore"
  acl: public_read
  skip_cleanup: true
  local_dir: build
  region: eu-west-1
branches:
  only:
  - master
